### ISSUE TITLE
CVAT - Uploading Annotations Error

### ISSUE THREAD

**Issue by MohamadHam** [openvinotoolkit/cvat#4433]
Hello there, 

I'm writing to you because we have been facing an issue with the tool CVAT. When we try to upload the annotations to the video. it gives us the following error:

_" Could not upload annotation for the task 9607
Error: Request failed with status code 400. "Could not match item id: 'RGBCAM1-20210602-20210629/0000655' with any task frame\n"._

I would really appreciate it if you have any idea on how we can fix this. Thanks!

**Comment by bsekachev** [comment]
@klakhov 
Could you please look at the issue?

**Comment by nmanovic** [comment]
@MohamadHam , could you please share with us a minimal example to reproduce? Just create a task on cvat.org and send us the annotation file with the link on your task.

**Comment by MohamadHam** [comment]
@nmanovic Thanks for getting back to me. I have tried now using cvat.org and tried to upload the annotations and it worked just fine. Now I'm wondering if you have any clue on why it did not work on the platform that's located on our internal server? 

When we try to upload the annotations to the video. it gives us the following error:

" Could not upload annotation for the task 9607
Error: Request failed with status code 400. "Could not match item id: 'RGBCAM1-20210602-20210629/0000655' with any task frame\n".


Thanks!

**Comment by nmanovic** [comment]
@MohamadHam , which CVAT version do you use?

**Comment by MohamadHam** [comment]
Server version: 1.4

Core version: 3.12.1

Canvas version: 2.4.3

UI version: 1.19.1

**Comment by nmanovic** [comment]
@MohamadHam , it is very old. The current version is v2.0.0 (released last week). At the end of previous year we released v1.7.

**Comment by MohamadHam** [comment]
Hello @nmanovic, I'm writing to inform you that we have updated the tool and yet the same issue when uploading annotations is not resolved.  :(

**Error message:** 

Could not upload annotation for the [task 1](http://cvat.subul.org:8080/tasks/1)
Error: Request failed with status code 400. "Could not match item id: 'RGBCAM1-20210602-20210629/0000655' with any task frame\n".
----
**Tool Version:**

Server version: 2.0
Core version: 4.2.1
Canvas version: 2.13.1
UI version: 1.36.0 

Any idea how we can solve the issue? Thanks!

**Comment by nmanovic** [comment]
@MohamadHam , could you please check that you really have the item in the task on your CVAT instance?

**Comment by MohamadHam** [comment]
@nmanovic, I have now tried to upload the annotations to a diff video on the same tool. And it worked fine. I'm wondering if the video itself has the issue as it's relatively large. 

The actual video that gives error is 176 MB - I have tried to upload the annotations on a smaller video 5 MB and it worked just fine. I'm wondering if the size of the video is the issue, if yes, please provide any solutions, and if not, please advise what the issue could be. Thanks!
